version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9
  jobs:
    pre_build:
      - pip install . # Need access to version information

sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/environment_docs.yml
